### ISSUE TITLE
Incorrect parameters in README

### ISSUE THREAD

**Issue by michalsimek** [SamsungSLAV/boruta#4]
When boruta runs it expects different parameters then the one listed in README

Here is the patch.

diff --git a/README b/README
index 8bd99ff1c95a..61cf6ea1a9de 100644
--- a/README
+++ b/README
@@ -97,7 +97,7 @@ Using Boruta
 
 #. Start Boruta server substituting your addresses and ports::
 
-      $ ./boruta --api-address=127.0.0.1:8487 --rpc-address=192.168.0.1:7175
+      $ ./boruta -api-addr=127.0.0.1:8487 -rpc-addr=192.168.0.1:7175
 
 #. Connect to your MuxPi_ and create directory for Dryad agent settings
    on the MuxPi_::

**Comment by maciejaszek** [comment]
@michalsimek Would send this patch as a pull request? Otherwise would you like some credits in commit message (other that Closes link)?

**Comment by michalsimek** [comment]
New pull request in place.
